name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.1.0'

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: Lint HTML
        run: htmlhint index.html

      - name: Install retire.js
        run: npm install -g retire

      - name: Security Scan with retire.js
        run: retire

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket
        run: |
          aws s3api create-bucket --bucket ${{ secrets.S3_BUCKET_NAME }} --region ${{ secrets.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }} || true

      - name: Sync S3 Bucket
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --exclude ".git/*" --delete

      - name: Create CloudFront Distribution
        id: create_cf
        run: |
          DISTRIBUTION_ID=$(aws cloudfront create-distribution \
            --origin-domain-name ${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com \
            --default-root-object index.html \
            --query 'Distribution.Id' --output text)
          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"
